# Generated by Django 4.1.4 on 2023-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myproject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("phonenumber", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("log_id", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Teacherslog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
    ]
